spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

  zipkin:
    baseUrl: http://localhost:9411/
server:
  port: 8765
