spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 8765
