server:
  port: 8003


spring:
  zipkin:
    base-url: http://localhost:9411/

  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:postgresql://localhost:5432/accounting-app-db
    #    url: ${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/${DATABASENAME}
    #    username: ${MYSQL_DB_USERNAME}
    #    password: ${MYSQL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-caskgq7d17c713thblhg-a.frankfurt-postgres.render.com/api_accounting_db
    username: admin
    password: dVKMUEqWPSRUjUY5JvHlZ428a4oFERhI

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
