server:
  port: 8001

spring:
  zipkin:
    base-url: http://localhost:9411/
  datasource:
    url: jdbc:postgresql://localhost:5432/accounting-app-db
    username: postgres
    password: Ankara3302
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
