server:
  port: 8001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accounting-app-user-db
    username: postgres
    password: 2754
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  zipkin:
    baseUrl: http://localhost:9411/